name: MNIST MLOps

on:
  push:
    branches: [main]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Train model
        run: python model/train.py
      - name: Deploy model
        run: python model/deploy.py
      - name: Update deployment status
        uses: rtCamp/github-deployment-status@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment_url: http://example.com
          state: success
